---
collections:
  - name: infra.support_assist
    source: https://github.com/redhat-cop/infra.support_assist.git
    version: devel
    type: git
  - name: community.general
  - name: ansible.windows
...
