---
- name: Monitor Proxmox for Stopped Instances
  hosts: localhost
  vars:
    # Proxmox Connection Variables - Update these for your environment
    proxmox_host: "192.168.1.100:8006"       # Your Proxmox IP:Port
    proxmox_node: "pve"                      # Your Node Name (e.g., pve)
    proxmox_user: "root@pam"                 # Your User
    proxmox_token_id: "ansible"              # Token ID you created
    proxmox_token_secret: "YOUR_SECRET_UUID" # The UUID secret
    proxmox_verify_ssl: false               # Set true if you have valid certs
    proxmox_poll_delay: 30                  # Poll every 30 seconds
  sources:
    - name: proxmox_monitor
      # Point to the directory containing your python script
      source_file: sources/proxmox_monitor.py
      args:
        host: "{{ proxmox_host }}"
        node: "{{ proxmox_node }}"
        user: "{{ proxmox_user }}"
        token_id: "{{ proxmox_token_id }}"
        token_secret: "{{ proxmox_token_secret }}"
        verify_ssl: "{{ proxmox_verify_ssl }}"
        delay: "{{ proxmox_poll_delay }}"

  rules:
    - name: Remediate Stopped VM (Unexpected Shutdown/Crash)
      condition: >
        event.proxmox.type == "vm" and
        event.proxmox.status == "stopped" and
        event.proxmox.previous_status == "running" and
        event.meta.event_type == "vm_stopped_unexpectedly"
      action:
        run_playbook:
          name: playbooks/start_proxmox_instance.yml
          extra_vars:
            target_vmid: "{{ event.proxmox.vmid }}"
            target_node: "{{ event.proxmox.node }}"
            vm_name: "{{ event.proxmox.name }}"
            instance_type: "vm"
            proxmox_host: "{{ proxmox_host }}"
            proxmox_node: "{{ proxmox_node }}"
            proxmox_user: "{{ proxmox_user }}"
            proxmox_token_id: "{{ proxmox_token_id }}"
            proxmox_token_secret: "{{ proxmox_token_secret }}"
            proxmox_verify_ssl: "{{ proxmox_verify_ssl }}"

    - name: Remediate Stopped LXC (Unexpected Shutdown/Crash)
      condition: >
        event.proxmox.type == "lxc" and
        event.proxmox.status == "stopped" and
        event.proxmox.previous_status == "running" and
        event.meta.event_type == "vm_stopped_unexpectedly"
      action:
        run_playbook:
          name: playbooks/start_proxmox_instance.yml
          extra_vars:
            target_vmid: "{{ event.proxmox.vmid }}"
            target_node: "{{ event.proxmox.node }}"
            vm_name: "{{ event.proxmox.name }}"
            instance_type: "lxc"
            proxmox_host: "{{ proxmox_host }}"
            proxmox_node: "{{ proxmox_node }}"
            proxmox_user: "{{ proxmox_user }}"
            proxmox_token_id: "{{ proxmox_token_id }}"
            proxmox_token_secret: "{{ proxmox_token_secret }}"
            proxmox_verify_ssl: "{{ proxmox_verify_ssl }}"
...
